#!/usr/bin/python3
import sys
from source.apt.configuration import get_configured_apt
from source.dnf.configuration import get_configured_dnf


from source.utils import get_os_data


def main(args=None):
    """
    Run the appropriate package manager.

    :param args: # TODO
    """
    os_data = get_os_data()
    requirements = {}
    refresh_args = []
    upgrade_args = []

    if os_data["os_family"] == "Debian":
        pkg_mng = get_configured_apt(os_data, requirements)
    elif os_data["os_family"] == "RedHat":
        pkg_mng = get_configured_dnf(os_data, requirements)
    else:
        raise NotImplementedError(
            "Only Debian and RedHat based os is supported.")

    # TODO config here
    return_code = pkg_mng.upgrade(refresh=True,
                                  hard_fail=True,
                                  remove_obsolete=True,
                                  requirements=requirements,
                                  refresh_args=refresh_args,
                                  upgrade_args=upgrade_args)
    # TODO clean config
    # TODO
    with open(pkg_mng.log_path) as f:
        print("".join(f.readlines()))

    return return_code


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))  # TODO argument parser
